# Imagem base do Ubuntu mais recente
FROM ubuntu:latest

# Atualiza o sistema e instala os pacotes bind9 e dnsutils
RUN apt-get update && apt-get install -y bind9 dnsutils

# Copia o arquivo named.conf.options para o diretório /etc/bind/named.conf.options
COPY named.conf.options /etc/bind/named.conf.options

# Expõe as portas 53/tcp e 53/udp
EXPOSE 53/tcp
EXPOSE 53/udp

# Comando para iniciar o serviço named
CMD ["/usr/sbin/named", "-g", "-c", "/etc/bind/named.conf", "-u", "bind"]